create database practice

use practice


-- SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE'

SELECT sobjects.name
FROM sysobjects sobjects
WHERE sobjects.xtype = 'U'

GO
DROP TABLE IF EXISTS tbl_Treatment;
GO
DROP TABLE IF EXISTS tbl_Procedure;
GO
DROP TABLE IF EXISTS tbl_Pet;
GO
DROP TABLE IF EXISTS tbl_Owner;

GO
CREATE TABLE tbl_Owner(
    OWNERID INT IDENTITY(1,1),
    SURNAME NVARCHAR(50),
    FIRSTNAME NVARCHAR(50),
    PHONE INT,
    USERNAME NVARCHAR(50),
    PASSWORD NVARCHAR(50),
    ADMIN BIT,
    PRIMARY KEY (OWNERID),
);

GO
CREATE TABLE tbl_Procedure(
    PROCEDUREID INT,
    DESCRIPTION NVARCHAR(150),
    PRICE DECIMAL,
    PRIMARY KEY (PROCEDUREID)
);

GO
CREATE TABLE tbl_Pet(
    PETNAME NVARCHAR(50),
    OWNERID INT,
    TYPE NVARCHAR(50),
    PRIMARY KEY (PETNAME, OWNERID),
    FOREIGN KEY (OWNERID) REFERENCES tbl_Owner
);

GO
CREATE TABLE tbl_Treatment(
    OWNERID INT,
    PETNAME NVARCHAR(50),
    PROCEDUREID INT,
    DATE DATE,
    NOTES NVARCHAR(150),
    PAYMENT NVARCHAR(50),
    PRIMARY KEY (DATE, PROCEDUREID, PETNAME, OWNERID),
    FOREIGN KEY (PROCEDUREID) REFERENCES tbl_Procedure,
    FOREIGN KEY (PETNAME, OWNERID) REFERENCES tbl_Pet
);

select * from tbl_Owner



INSERT INTO tbl_Owner( SURNAME, FIRSTNAME, PHONE, USERNAME, [PASSWORD], ADMIN) VALUES ('Sinatra','Frank', 400111222, 'SinF', 'dude', 0);
INSERT INTO tbl_Owner( SURNAME, FIRSTNAME, PHONE, USERNAME, [PASSWORD], ADMIN) VALUES ('Ellington','Duke', 400222333, 'papaG', 'guy', 0);
INSERT INTO tbl_Owner( SURNAME, FIRSTNAME, PHONE, USERNAME, [PASSWORD], ADMIN) VALUES ('Fitzgerald','Ella', 400333444, 'fitz', 'man', 0);
INSERT INTO tbl_Owner( SURNAME, FIRSTNAME, PHONE, USERNAME, [PASSWORD], ADMIN) VALUES ('STAFF','ACCOUNT', 000000000, 'admin', 'admin', 1);

INSERT INTO tbl_Pet(OWNERID, PETNAME, TYPE) VALUES (1 ,'Buster', 'Dog');
INSERT INTO tbl_Pet(OWNERID, PETNAME, TYPE) VALUES (1 ,'Fluffy', 'Cat');
INSERT INTO tbl_Pet(OWNERID, PETNAME, TYPE) VALUES (2 ,'Stew', 'Rabbit');
INSERT INTO tbl_Pet(OWNERID, PETNAME, TYPE) VALUES (3 ,'Buster', 'Echidna');

INSERT INTO tbl_Procedure(PROCEDUREID, DESCRIPTION, PRICE) VALUES (01 ,'Rabies Vaccination', 24.00);
INSERT INTO tbl_Procedure(PROCEDUREID, DESCRIPTION, PRICE) VALUES (10 ,'Examine and Treat Wound', 30.00);
INSERT INTO tbl_Procedure(PROCEDUREID, DESCRIPTION, PRICE) VALUES (05 ,'Heart Worm Test', 25.00);
INSERT INTO tbl_Procedure(PROCEDUREID, DESCRIPTION, PRICE) VALUES (08 ,'Tetnus Vaccination', 17.00);

INSERT INTO tbl_Treatment(OWNERID, PETNAME, PROCEDUREID, DATE,NOTES,PAYMENT) VALUES (1, 'Buster', 01, '2017-06-20', 'Routine Vaccination', 22.00);
INSERT INTO tbl_Treatment(OWNERID, PETNAME, PROCEDUREID, DATE,NOTES,PAYMENT) VALUES (1, 'Buster', 01, '2018-05-15', 'Booster Shot', 24.00);
INSERT INTO tbl_Treatment(OWNERID, PETNAME, PROCEDUREID, DATE,NOTES,PAYMENT) VALUES (1, 'Fluffy', 10, '2018-05-10', 'Wounds sustained in apparent cat fight.', 30.00);
INSERT INTO tbl_Treatment(OWNERID, PETNAME, PROCEDUREID, DATE,NOTES,PAYMENT) VALUES (2, 'Stew', 10, '2018-05-10', 'Wounds sustained during attempt to cook the stew.', 30.00);
INSERT INTO tbl_Treatment(OWNERID, PETNAME, PROCEDUREID, DATE,NOTES,PAYMENT) VALUES (3, 'Buster', 08, '2017-06-20', 'Stepped on a Rusty Nail', 17.00);
INSERT INTO tbl_Treatment(OWNERID, PETNAME, PROCEDUREID, DATE,NOTES,PAYMENT) VALUES (3, 'Buster', 01, '2017-06-20', 'Routine Vaccination', 22.00);


GO

CREATE VIEW view_User AS
SELECT tbl_Owner.OWNERID, tbl_Owner.USERNAME, tbl_Owner.PASSWORD, tbl_Owner.ADMIN
FROM tbl_Owner

GO

CREATE VIEW view_Pets AS
SELECT tbl_Pet.OWNERID, tbl_Pet.PETNAME, tbl_Pet.[TYPE]
FROM tbl_Pet

select * from view_pets

drop view view_pets
drop view view_user